#+TITLE: 42s-atomic
#+AUTHOR: Stefanos Carlström
#+EMAIL: stefanos.carlstrom@gmail.com

A small library of routines for calculating interesting quantities
useful in Atomic Physics and Ultrafast Optics.

* Build instructions
  The HP42s =raw= files are generated by typing
  #+BEGIN_SRC sh
    rake
  #+END_SRC
  in a command line near you. Requires [[http://ruby-lang.org][Ruby]] and [[https://www.perl.org][Perl]] to work. The
  =raw= files are created in the subfolder =build/raw/=.

  To translate from text format to =raw= files, the [[file:./txt2raw.pl][txt2raw.pl]] by
  Vini Matangrano is used.

* Routines
  * =LELEV= :: Load [[file:./data/eVs.txt][first ionization energies]] (in eV) into a matrix
               named =ELEV=. (Data source: [[https://www.nist.gov/pml/atomic-spectra-database][NIST]])
  * =LCONST= :: Load constants useful for atomic units, etc. See
                [[file:./data/constants.yaml][constants.yaml]] for which constants are defined.
  * =OMEGAU= :: Given a wavelength λ in SI units, calculate the
                angular frequency ω = 2πc₀/λ, storing the result in
                atomic units in the variable =OMEGAU= and in
                electronvolts in =OMEGAEV=.
* Caveats
  These routines are only tested using [[http://thomasokken.com/free42/][Free42]], as I don't own a real
  HP42s device.
